apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-app-construction
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kaushikbl/web-app-construction.git
    targetRevision: main
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: ""
    kind: PersistentVolumeClaim
    jsonPointers:
    - /spec/volumeName
    - /status