apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongoDB
  namespace: dev

spec:
  replicas: 1
  revisionHistoryLimit: 2

  selector:
    matchLabels:
      app: mongoDB

  template:
    metadata:
      labels:
        app: mongoDB

    spec:
      containers:
        - name: mongoDB
          image: mongo:6.0
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"

          ports:
            - containerPort: 27017

          volumeMounts:
            - name: mongoDB-storage
              mountPath: /data/db

      volumes:
        - name: mongoDB-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
